version: "3.8"
services:
  app:
    build: .
    container_name: app
    volumes: 
      - .:/app/
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
