version: "3.8"
services:
  test:
    build: .
    container_name: app
    # volumes: 
    #   - .:/app/
  test-db:
    image: mysql:latest
    container_name: db
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
